# Generated by Django 4.0.4 on 2022-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_rename_auteur_film_realisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='dico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
