# Generated by Django 4.0.4 on 2022-05-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cat',
            field=models.CharField(choices=[('AC', 'Action'), ('AN', 'Animation'), ('AV', 'Aventure'), ('Ho', 'Horreur'), ('Fa', 'Fantastique'), ('SF', 'Science Fiction'), ('Ge', 'Guerre')], default=7, max_length=30),
            preserve_default=False,
        ),
    ]
