# Generated by Django 4.0.4 on 2022-05-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_site_resume_alter_film_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cat',
            field=models.CharField(choices=[('Action', 'Action'), ('Animation', 'Animation'), ('Aventure', 'Aventure'), ('Horreur', 'Horreur'), ('Fantastique', 'Fantastique'), ('Science Fiction', 'Science Fiction'), ('Geuerre', 'Guerre')], max_length=30),
        ),
    ]
