# Generated by Django 4.0.4 on 2022-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_alter_film_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imaurl',
            field=models.URLField(default=200),
            preserve_default=False,
        ),
    ]
