# Generated by Django 4.0.4 on 2022-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_film_imaurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imaurl',
            field=models.URLField(max_length=300),
        ),
    ]
