# Generated by Django 4.0.4 on 2022-05-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_alter_film_imaurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='film.site'),
        ),
    ]
